### ISSUE TITLE
Add Closure Compiler annotations

### ISSUE THREAD

**Issue by cvrebert** [twbs/mq4-hover-shim#13]
Also, might need to adjust the Gruntfile of the external project that incorporates this.

**Comment by kkirsche** [comment]
What does this specifically mean? Sorry, not familiar with 'closure compiler'. Thanks for your patience.

**Comment by cvrebert** [comment]
* https://developers.google.com/closure/compiler/
* https://developers.google.com/closure/compiler/docs/js-for-compiler

I would recommend you skip this issue, as I myself am not currently familiar with the Closure Compiler, and thus wouldn't be able to provide any useful guidance.

**Comment by kkirsche** [comment]
Fair. Thanks for the resources to read about this though :smiley:

**Comment by cvrebert** [comment]
Put on indefinite hold due to https://twitter.com/getbootstrap/status/595748426601598976
